name: Run notion-to-md.py Script Weekly

on:
  schedule:
    - cron: "0 0 * * 1"  # Run every Monday at midnight UTC

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the Project
        run: uv sync --all-extras --dev

      - name: Run notion-to-md.py script
        run: uv run python mkdocs-python/notion-to-md.py
