name: Run notion-to-md.py Script weekly
on:
  schedule:
    - cron: "0 0 * * 1"
  
  workflow_dispatch:

jobs:
  uv:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev
      
      - name: "Run notion-to-md.py script"
      - run: uv run python mkdocs-python/notion-to-md.py