name: Run notion-to-md.py Script Weekly

on:
  schedule:
    - cron: "0 0 * * 1"  # Run every Monday at midnight UTC

  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevents default token usage
          fetch-depth: 0  # Ensures full history for committing

      # Set up Git user
      - name: Configure Git
        run: |
          git config --global user.name "lukafilipxvic"
          git config --global user.email "lukafilipxvic@users.noreply.github.com"

      # Install uvicorn using the Astral setup-uv action
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      # Install project dependencies using uvicorn
      - name: Install the Project
        run: uv sync --all-extras --dev

      # Run the Python script
      - name: Run notion-to-md.py script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_BOOKS: ${{ secrets.NOTION_DATABASE_BOOKS }}
        run: uv run python mkdocs-python/notion-to-md.py

      # Check for changes
      - name: Check for Git Changes
        id: git_changes
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes detected."
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      # Commit and push changes
      - name: Commit and Push Changes
        if: env.has_changes == 'true'
        run: |
          git add .
          git commit -m "Automated updates from notion-to-md.py"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
